/* ============================================
   GAME EXPORTER & DOWNLOAD MANAGER
   Allows downloading HTML, CSS, JS, and full
   offline ZIP projects that run without internet.
   ============================================ */

import JSZip from 'jszip';

function triggerBrowserDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

export function downloadGameHtml(game) {
  const blob = new Blob([game.fullHtml], { type: 'text/html;charset=utf-8' });
  const safeName = (game.title || 'game').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  triggerBrowserDownload(blob, `${safeName}.html`);
}

export function downloadGameCss(game) {
  const blob = new Blob([game.css], { type: 'text/css;charset=utf-8' });
  triggerBrowserDownload(blob, 'style.css');
}

export function downloadGameJs(game) {
  const blob = new Blob([game.js], { type: 'application/javascript;charset=utf-8' });
  triggerBrowserDownload(blob, 'game.js');
}

export async function downloadGameZip(game) {
  const zip = new JSZip();

  const modularHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>${game.title}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  ${game.html}
  <script src="game.js"></script>
</body>
</html>`;

  const readme = `=====================================================
${game.title.toUpperCase()}
Generated by Study AI (FurqanNovaAI) Game Engine
=====================================================

HOW TO PLAY:
1. Double-click "index.html" in any web browser (Chrome, Edge, Firefox, Safari).
2. Works 100% OFFLINE - No internet connection or web server required!

GAME CONTROLS:
${game.controls}

DESCRIPTION:
${game.description}

FILES INCLUDED:
- index.html   (HTML5 structure and canvas viewport)
- style.css    (Responsive layout and arcade styling)
- game.js      (Complete game loop, collision physics & audio synthesis)

Enjoy playing!
`;

  zip.file('index.html', modularHtml);
  zip.file('style.css', game.css);
  zip.file('game.js', game.js);
  zip.file('README.txt', readme);

  const safeName = (game.title || 'game').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const content = await zip.generateAsync({ type: 'blob' });
  triggerBrowserDownload(content, `${safeName}-project.zip`);
}
